# Generated by Django 5.2.1 on 2025-05-22 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0002_rubric_subrubricmanager_superrubricmanager_subrubric_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubRubricManager',
        ),
        migrations.DeleteModel(
            name='SuperRubricManager',
        ),
    ]
