# Generated by Django 5.2.1 on 2025-05-27 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0003_alter_bb_is_active_alter_bb_rubric'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bb',
            options={'ordering': ['-created_at'], 'verbose_name': 'Объявление', 'verbose_name_plural': 'Объявления'},
        ),
    ]
